import {expect} from 'chai';
import {COMPANY_REGISTRATION_TYPES, COUNTRIES, DISTRICTS, EMPLOYMENT_TYPES, JOB_CATEGORIES, POSITION_LEVELS, SALARY_TYPES, SCHEMES, SUB_SCHEMES} from './mcf';

describe('mcf', () => {
  it('should have correct employment types', () => {
    expect(EMPLOYMENT_TYPES).to.deep.equal([
      {id: 7, employmentType: 'Permanent'},
      {id: 8, employmentType: 'Full Time'},
      {id: 5, employmentType: 'Part Time'},
      {id: 3, employmentType: 'Contract'},
      {id: 9, employmentType: 'Flexi-work'},
      {id: 2, employmentType: 'Temporary'},
      {id: 6, employmentType: 'Freelance'},
      {id: 10, employmentType: 'Internship'},
    ]);
  });
  it('should have correct position levels', () => {
    expect(POSITION_LEVELS).to.deep.equal([
      {id: 1, position: 'Senior Management'},
      {id: 2, position: 'Middle Management'},
      {id: 3, position: 'Manager'},
      {id: 7, position: 'Professional'},
      {id: 8, position: 'Senior Executive'},
      {id: 9, position: 'Executive'},
      {id: 10, position: 'Junior Executive'},
      {id: 11, position: 'Non-executive'},
      {id: 12, position: 'Fresh/entry level'},
    ]);
  });
  it('should have correct job categories', () => {
    expect(JOB_CATEGORIES).to.deep.equal([
      {id: 1, category: 'Accounting / Auditing / Taxation'},
      {id: 2, category: 'Admin / Secretarial'},
      {id: 3, category: 'Advertising / Media'},
      {id: 4, category: 'Architecture / Interior Design'},
      {id: 5, category: 'Banking and Finance'},
      {id: 6, category: 'Building and Construction'},
      {id: 7, category: 'Consulting'},
      {id: 8, category: 'Customer Service'},
      {id: 9, category: 'Design'},
      {id: 10, category: 'Education and Training'},
      {id: 11, category: 'Engineering'},
      {id: 12, category: 'Entertainment'},
      {id: 13, category: 'Environment / Health'},
      {id: 14, category: 'Events / Promotions'},
      {id: 15, category: 'F&B'},
      {id: 16, category: 'General Management'},
      {id: 17, category: 'General Work'},
      {id: 18, category: 'Healthcare / Pharmaceutical'},
      {id: 19, category: 'Hospitality'},
      {id: 20, category: 'Human Resources'},
      {id: 21, category: 'Information Technology'},
      {id: 22, category: 'Insurance'},
      {id: 23, category: 'Legal'},
      {id: 24, category: 'Logistics / Supply Chain'},
      {id: 25, category: 'Manufacturing'},
      {id: 26, category: 'Marketing / Public Relations'},
      {id: 27, category: 'Medical / Therapy Services'},
      {id: 28, category: 'Personal Care / Beauty'},
      {id: 29, category: 'Professional Services'},
      {id: 30, category: 'Public / Civil Service'},
      {id: 31, category: 'Purchasing / Merchandising'},
      {id: 32, category: 'Real Estate / Property Management'},
      {id: 33, category: 'Repair and Maintenance'},
      {id: 34, category: 'Risk Management'},
      {id: 35, category: 'Sales / Retail'},
      {id: 36, category: 'Sciences / Laboratory / R&D'},
      {id: 37, category: 'Security and Investigation'},
      {id: 38, category: 'Social Services'},
      {id: 39, category: 'Telecommunications'},
      {id: 40, category: 'Travel / Tourism'},
      {id: 41, category: 'Others'},
    ]);
  });
  it('should have correct schemes', () => {
    expect(SCHEMES).to.deep.equal([
      {id: 1, scheme: 'P-Max', startDate: '1977-05-25', expiryDate: '2055-05-04'},
      {id: 2, scheme: 'Professional Conversion Programme (PCP)', startDate: '1977-05-25', expiryDate: '2055-05-04'},
      {id: 3, scheme: 'Career Trial', startDate: '1977-05-25', expiryDate: '2055-05-04'},
      {id: 4, scheme: 'Career Support', startDate: '1977-05-25', expiryDate: '2055-05-04'},
    ]);
  });
  it('should have correct districts', () => {
    expect(DISTRICTS).to.deep.equal([
      {
        id: 1,
        location: 'D01 Cecil, Marina, People’s Park, Raffles Place',
        region: 'Central',
        sectors: ['01', '02', '03', '04', '05', '06'],
      },
      {
        id: 2,
        location: 'D02 Anson, Tanjong Pagar',
        region: 'Central',
        sectors: ['07', '08'],
      },
      {
        id: 3,
        location: 'D03 Queenstown, Tiong Bahru',
        region: 'South',
        sectors: ['14', '15', '16'],
      },
      {
        id: 4,
        location: 'D04 Harbourfront,Telok Blangah, Sentosa Island',
        region: 'South',
        sectors: ['09', '10'],
      },
      {
        id: 5,
        location: 'D05 Clementi New Town, Hong Leong Garden, Pasir Panjang',
        region: 'South',
        sectors: ['11', '12', '13'],
      },
      {
        id: 6,
        location: 'D06 Beach Road, High Street',
        region: 'East',
        sectors: ['17'],
      },
      {
        id: 7,
        location: 'D07 Golden Mile, Middle Road',
        region: 'East',
        sectors: ['18', '19'],
      },
      {
        id: 8,
        location: 'D08 Little India',
        region: 'Central',
        sectors: ['20', '21'],
      },
      {
        id: 9,
        location: 'D09 Cairnhill, Orchard, River Valley',
        region: 'Central',
        sectors: ['22', '23'],
      },
      {
        id: 10,
        location: 'D10 Ardmore, Bukit Timah, Holland Road, Tanglin',
        region: 'Central',
        sectors: ['24', '25', '26', '27'],
      },
      {
        id: 11,
        location: 'D11 Novena, Thomson, Watten Estate',
        region: 'Central',
        sectors: ['28', '29', '30'],
      },
      {
        id: 12,
        location: 'D12 Balestier, Serangoon, Toa Payoh',
        region: 'Central',
        sectors: ['31', '32', '33'],
      },
      {
        id: 13,
        location: 'D13 Macpherson, Braddell',
        region: 'Central',
        sectors: ['34', '35', '36', '37'],
      },
      {
        id: 14,
        location: 'D14 Geylang, Eunos',
        region: 'East',
        sectors: ['38', '39', '40', '41'],
      },
      {
        id: 15,
        location: 'D15 Katong, Joo Chiat, Amber Road',
        region: 'East',
        sectors: ['42', '43', '44', '45'],
      },
      {
        id: 16,
        location: 'D16 Upper East Coast, Bedok, Eastwood, Kew Drive',
        region: 'East',
        sectors: ['46', '47', '48'],
      },
      {
        id: 17,
        location: 'D17 Loyang, Changi',
        region: 'East',
        sectors: ['49', '50', '81', '91'],
      },
      {
        id: 18,
        location: 'D18 Tampines, Pasir Ris',
        region: 'East',
        sectors: ['51', '52'],
      },
      {
        id: 19,
        location: 'D19 Serangoon Garden, Hougang, Sengkang, Punggol',
        region: 'North',
        sectors: ['53', '54', '55', '82'],
      },
      {
        id: 20,
        location: 'D20 Bishan, Ang Mo Kio',
        region: 'North',
        sectors: ['56', '57'],
      },
      {
        id: 21,
        location: 'D21 Upper Bukit Timah, Clementi Park, Ulu Pandan',
        region: 'West',
        sectors: ['58', '59'],
      },
      {
        id: 22,
        location: 'D22 Jurong, Jurong Island, Tuas',
        region: 'West',
        sectors: ['60', '61', '62', '63', '64'],
      },
      {
        id: 23,
        location: 'D23 Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang',
        region: 'West',
        sectors: ['65', '66', '67', '68'],
      },
      {
        id: 24,
        location: 'D24 Lim Chu Kang, Tengah',
        region: 'West',
        sectors: ['69', '70', '71'],
      },
      {
        id: 25,
        location: 'D25 Kranji, Woodgrove, Woodlands',
        region: 'North',
        sectors: ['72', '73'],
      },
      {
        id: 26,
        location: 'D26 Upper Thomson, Springleaf',
        region: 'North',
        sectors: ['77', '78'],
      },
      {
        id: 27,
        location: 'D27 Yishun, Sembawang',
        region: 'North',
        sectors: ['75', '76'],
      },
      {
        id: 28,
        location: 'D28 Seletar',
        region: 'North',
        sectors: ['79', '80'],
      },
      {
        id: 998,
        location: 'Islandwide',
        region: 'Islandwide',
        sectors: [],
      },
      {
        id: 999,
        location: 'Overseas',
        region: 'Overseas',
        sectors: [],
      },
    ]);
  });
  it('should have correct countries', () => {
    expect(COUNTRIES).to.deep.equal([
      {
        code: 'SG',
        codeNumber: 65,
        description: 'Singapore',
      },
      {
        code: 'AF',
        codeNumber: 93,
        description: 'Afghanistan',
      },
      {
        code: 'AL',
        codeNumber: 355,
        description: 'Albania',
      },
      {
        code: 'DZ',
        codeNumber: 213,
        description: 'Algeria',
      },
      {
        code: 'AS',
        codeNumber: 1,
        description: 'American Samoa',
      },
      {
        code: 'AD',
        codeNumber: 376,
        description: 'Andorra',
      },
      {
        code: 'AO',
        codeNumber: 244,
        description: 'Angola',
      },
      {
        code: 'AI',
        codeNumber: 1,
        description: 'Anguilla',
      },
      {
        code: 'AG',
        codeNumber: 1,
        description: 'Antigua',
      },
      {
        code: 'AR',
        codeNumber: 54,
        description: 'Argentina',
      },
      {
        code: 'AM',
        codeNumber: 374,
        description: 'Armenia',
      },
      {
        code: 'AB',
        codeNumber: 297,
        description: 'Aruba',
      },
      {
        code: 'AU',
        codeNumber: 61,
        description: 'Australia',
      },
      {
        code: 'AT',
        codeNumber: 43,
        description: 'Austria',
      },
      {
        code: 'AZ',
        codeNumber: 994,
        description: 'Azerbaijan',
      },
      {
        code: 'BS',
        codeNumber: 1,
        description: 'Bahamas',
      },
      {
        code: 'BH',
        codeNumber: 973,
        description: 'Bahrain',
      },
      {
        code: 'BD',
        codeNumber: 880,
        description: 'Bangladesh',
      },
      {
        code: 'BB',
        codeNumber: 1,
        description: 'Barbados',
      },
      {
        code: 'BL',
        codeNumber: 375,
        description: 'Belarus',
      },
      {
        code: 'BE',
        codeNumber: 32,
        description: 'Belgium',
      },
      {
        code: 'BZ',
        codeNumber: 501,
        description: 'Belize',
      },
      {
        code: 'BJ',
        codeNumber: 229,
        description: 'Benin',
      },
      {
        code: 'BM',
        codeNumber: 1,
        description: 'Bermuda',
      },
      {
        code: 'BT',
        codeNumber: 975,
        description: 'Bhutan',
      },
      {
        code: 'BO',
        codeNumber: 591,
        description: 'Bolivia',
      },
      {
        code: 'BA',
        codeNumber: 387,
        description: 'Bosnia-Herzegovina',
      },
      {
        code: 'BW',
        codeNumber: 267,
        description: 'Botswana',
      },
      {
        code: 'BR',
        codeNumber: 55,
        description: 'Brazil',
      },
      {
        code: 'BQ',
        codeNumber: 0,
        description: 'British Antarctic Territory',
      },
      {
        code: 'IO',
        codeNumber: 246,
        description: 'British Indian Ocean Territory',
      },
      {
        code: 'VG',
        codeNumber: 1,
        description: 'British Virgin Islands',
      },
      {
        code: 'BN',
        codeNumber: 673,
        description: 'Brunei',
      },
      {
        code: 'BG',
        codeNumber: 359,
        description: 'Bulgaria',
      },
      {
        code: 'BF',
        codeNumber: 226,
        description: 'Burkina Faso',
      },
      {
        code: 'BI',
        codeNumber: 257,
        description: 'Burundi',
      },
      {
        code: 'KA',
        codeNumber: 855,
        description: 'Cambodia',
      },
      {
        code: 'CM',
        codeNumber: 237,
        description: 'Cameroon',
      },
      {
        code: 'CA',
        codeNumber: 1,
        description: 'Canada',
      },
      {
        code: 'CT',
        codeNumber: 0,
        description: 'Canton & Enderbury Islands',
      },
      {
        code: 'CV',
        codeNumber: 238,
        description: 'Cape Verde',
      },
      {
        code: 'KY',
        codeNumber: 1,
        description: 'Cayman Islands',
      },
      {
        code: 'CF',
        codeNumber: 236,
        description: 'Central African Republic',
      },
      {
        code: 'TD',
        codeNumber: 235,
        description: 'Chad',
      },
      {
        code: 'CD',
        codeNumber: 0,
        description: 'Channel Islands',
      },
      {
        code: 'CL',
        codeNumber: 56,
        description: 'Chile',
      },
      {
        code: 'CN',
        codeNumber: 86,
        description: 'China',
      },
      {
        code: 'CX',
        codeNumber: 61,
        description: 'Christmas Island',
      },
      {
        code: 'CC',
        codeNumber: 61,
        description: 'Cocos Keeling Island',
      },
      {
        code: 'CO',
        codeNumber: 57,
        description: 'Colombia',
      },
      {
        code: 'KM',
        codeNumber: 269,
        description: 'Comoros',
      },
      {
        code: 'CG',
        codeNumber: 242,
        description: 'Congo',
      },
      {
        code: 'CK',
        codeNumber: 682,
        description: 'Cook Islands',
      },
      {
        code: 'CR',
        codeNumber: 506,
        description: 'Costa Rica',
      },
      {
        code: 'CB',
        codeNumber: 385,
        description: 'Croatia',
      },
      {
        code: 'CU',
        codeNumber: 53,
        description: 'Cuba',
      },
      {
        code: 'CY',
        codeNumber: 357,
        description: 'Cyprus',
      },
      {
        code: 'CZ',
        codeNumber: 420,
        description: 'Czech Republic',
      },
      {
        code: 'DK',
        codeNumber: 45,
        description: 'Denmark',
      },
      {
        code: 'DJ',
        codeNumber: 253,
        description: 'Djibouti',
      },
      {
        code: 'DM',
        codeNumber: 1,
        description: 'Dominica',
      },
      {
        code: 'DO',
        codeNumber: 1,
        description: 'Dominican Republic',
      },
      {
        code: 'TP',
        codeNumber: 670,
        description: 'East Timor',
      },
      {
        code: 'EC',
        codeNumber: 593,
        description: 'Ecuador',
      },
      {
        code: 'EG',
        codeNumber: 20,
        description: 'Egypt',
      },
      {
        code: 'SV',
        codeNumber: 503,
        description: 'El Salvador',
      },
      {
        code: 'GQ',
        codeNumber: 240,
        description: 'Equatorial Guinea',
      },
      {
        code: 'ER',
        codeNumber: 291,
        description: 'Eritrea',
      },
      {
        code: 'EN',
        codeNumber: 372,
        description: 'Estonia',
      },
      {
        code: 'ET',
        codeNumber: 251,
        description: 'Ethiopia',
      },
      {
        code: 'FO',
        codeNumber: 298,
        description: 'Faeroe Islands',
      },
      {
        code: 'FK',
        codeNumber: 500,
        description: 'Falkland Islands',
      },
      {
        code: 'FJ',
        codeNumber: 679,
        description: 'Fiji',
      },
      {
        code: 'FI',
        codeNumber: 358,
        description: 'Finland',
      },
      {
        code: 'FR',
        codeNumber: 33,
        description: 'France',
      },
      {
        code: 'GF',
        codeNumber: 594,
        description: 'French Guiana',
      },
      {
        code: 'PF',
        codeNumber: 689,
        description: 'French Polynesia',
      },
      {
        code: 'FQ',
        codeNumber: 298,
        description: 'French Southern & Antarctic Territories',
      },
      {
        code: 'GA',
        codeNumber: 241,
        description: 'Gabon',
      },
      {
        code: 'GM',
        codeNumber: 220,
        description: 'Gambia',
      },
      {
        code: 'GZ',
        codeNumber: 0,
        description: 'Gaza',
      },
      {
        code: 'GO',
        codeNumber: 995,
        description: 'Georgia',
      },
      {
        code: 'DG',
        codeNumber: 49,
        description: 'Germany',
      },
      {
        code: 'GH',
        codeNumber: 233,
        description: 'Ghana',
      },
      {
        code: 'GI',
        codeNumber: 350,
        description: 'Gibraltar',
      },
      {
        code: 'GR',
        codeNumber: 30,
        description: 'Greece',
      },
      {
        code: 'GL',
        codeNumber: 299,
        description: 'Greenland',
      },
      {
        code: 'GD',
        codeNumber: 1,
        description: 'Grenada',
      },
      {
        code: 'GP',
        codeNumber: 590,
        description: 'Guadeloupe',
      },
      {
        code: 'GU',
        codeNumber: 1,
        description: 'Guam',
      },
      {
        code: 'GT',
        codeNumber: 502,
        description: 'Guatemala',
      },
      {
        code: 'GK',
        codeNumber: 44,
        description: 'Guernsey',
      },
      {
        code: 'GN',
        codeNumber: 224,
        description: 'Guinea',
      },
      {
        code: 'GW',
        codeNumber: 245,
        description: 'Guinea-Bissau',
      },
      {
        code: 'GY',
        codeNumber: 592,
        description: 'Guyana',
      },
      {
        code: 'HT',
        codeNumber: 509,
        description: 'Haiti',
      },
      {
        code: 'HM',
        codeNumber: 0,
        description: 'Heard Island & McDonald Islands',
      },
      {
        code: 'HN',
        codeNumber: 504,
        description: 'Honduras',
      },
      {
        code: 'HK',
        codeNumber: 852,
        description: 'Hong Kong',
      },
      {
        code: 'HS',
        codeNumber: 852,
        description: 'Hong Kong SAR',
      },
      {
        code: 'HU',
        codeNumber: 36,
        description: 'Hungary',
      },
      {
        code: 'IS',
        codeNumber: 354,
        description: 'Iceland',
      },
      {
        code: 'IN',
        codeNumber: 91,
        description: 'India',
      },
      {
        code: 'ID',
        codeNumber: 62,
        description: 'Indonesia',
      },
      {
        code: 'IR',
        codeNumber: 98,
        description: 'Iran',
      },
      {
        code: 'IQ',
        codeNumber: 964,
        description: 'Iraq',
      },
      {
        code: 'IE',
        codeNumber: 353,
        description: 'Ireland',
      },
      {
        code: 'MM',
        codeNumber: 44,
        description: 'Isle Of Man',
      },
      {
        code: 'IL',
        codeNumber: 972,
        description: 'Israel',
      },
      {
        code: 'IT',
        codeNumber: 39,
        description: 'Italy',
      },
      {
        code: 'CI',
        codeNumber: 225,
        description: 'Ivory Coast',
      },
      {
        code: 'JM',
        codeNumber: 1,
        description: 'Jamaica',
      },
      {
        code: 'JP',
        codeNumber: 962,
        description: 'Japan',
      },
      {
        code: 'JT',
        codeNumber: 81,
        description: 'Johnston Island',
      },
      {
        code: 'JO',
        codeNumber: 1,
        description: 'Jordan',
      },
      {
        code: 'KZ',
        codeNumber: 7,
        description: 'Kazakhstan',
      },
      {
        code: 'KE',
        codeNumber: 254,
        description: 'Kenya',
      },
      {
        code: 'KG',
        codeNumber: 0,
        description: 'Kirghizia',
      },
      {
        code: 'KI',
        codeNumber: 686,
        description: 'Kiribati',
      },
      {
        code: 'KP',
        codeNumber: 82,
        description: 'Korea, North',
      },
      {
        code: 'KR',
        codeNumber: 856,
        description: 'Korea, South',
      },
      {
        code: 'KV',
        codeNumber: 383,
        description: 'Kosovo',
      },
      {
        code: 'KW',
        codeNumber: 965,
        description: 'Kuwait',
      },
      {
        code: 'KS',
        codeNumber: 996,
        description: 'Kyrgyzstan',
      },
      {
        code: 'LA',
        codeNumber: 218,
        description: 'Laos',
      },
      {
        code: 'LV',
        codeNumber: 371,
        description: 'Latvia',
      },
      {
        code: 'LB',
        codeNumber: 961,
        description: 'Lebanon',
      },
      {
        code: 'LS',
        codeNumber: 266,
        description: 'Lesotho',
      },
      {
        code: 'LR',
        codeNumber: 231,
        description: 'Liberia',
      },
      {
        code: 'LY',
        codeNumber: 850,
        description: 'Libya',
      },
      {
        code: 'LI',
        codeNumber: 423,
        description: 'Liechtenstein',
      },
      {
        code: 'LH',
        codeNumber: 370,
        description: 'Lithuania',
      },
      {
        code: 'LU',
        codeNumber: 352,
        description: 'Luxembourg',
      },
      {
        code: 'MO',
        codeNumber: 853,
        description: 'Macao',
      },
      {
        code: 'MF',
        codeNumber: 853,
        description: 'Macau SAR',
      },
      {
        code: 'MB',
        codeNumber: 0,
        description: 'Macedonia',
      },
      {
        code: 'MG',
        codeNumber: 261,
        description: 'Madagascar',
      },
      {
        code: 'MW',
        codeNumber: 265,
        description: 'Malawi',
      },
      {
        code: 'MY',
        codeNumber: 60,
        description: 'Malaysia',
      },
      {
        code: 'MV',
        codeNumber: 960,
        description: 'Maldives',
      },
      {
        code: 'ML',
        codeNumber: 223,
        description: 'Mali',
      },
      {
        code: 'MT',
        codeNumber: 356,
        description: 'Malta',
      },
      {
        code: 'MH',
        codeNumber: 692,
        description: 'Marshall Islands',
      },
      {
        code: 'MQ',
        codeNumber: 596,
        description: 'Martinique',
      },
      {
        code: 'MR',
        codeNumber: 222,
        description: 'Mauritania',
      },
      {
        code: 'MU',
        codeNumber: 230,
        description: 'Mauritius',
      },
      {
        code: 'ME',
        codeNumber: 262,
        description: 'Mayotte',
      },
      {
        code: 'MX',
        codeNumber: 52,
        description: 'Mexico',
      },
      {
        code: 'MI',
        codeNumber: 1,
        description: 'Midway Islands',
      },
      {
        code: 'MD',
        codeNumber: 373,
        description: 'Moldova',
      },
      {
        code: 'MC',
        codeNumber: 377,
        description: 'Monaco',
      },
      {
        code: 'MN',
        codeNumber: 976,
        description: 'Mongolia',
      },
      {
        code: 'MJ',
        codeNumber: 382,
        description: 'Montenegro',
      },
      {
        code: 'MS',
        codeNumber: 1,
        description: 'Montserrat',
      },
      {
        code: 'MA',
        codeNumber: 212,
        description: 'Morocco',
      },
      {
        code: 'MZ',
        codeNumber: 258,
        description: 'Mozambique',
      },
      {
        code: 'BU',
        codeNumber: 95,
        description: 'Myanmar',
      },
      {
        code: 'NA',
        codeNumber: 264,
        description: 'Namibia',
      },
      {
        code: 'NR',
        codeNumber: 674,
        description: 'Nauru',
      },
      {
        code: 'NP',
        codeNumber: 977,
        description: 'Nepal',
      },
      {
        code: 'NL',
        codeNumber: 31,
        description: 'Netherlands',
      },
      {
        code: 'AN',
        codeNumber: 599,
        description: 'Netherlands Antililles',
      },
      {
        code: 'NC',
        codeNumber: 687,
        description: 'New Caledonia',
      },
      {
        code: 'NZ',
        codeNumber: 64,
        description: 'New Zealand',
      },
      {
        code: 'NI',
        codeNumber: 505,
        description: 'Nicaragua',
      },
      {
        code: 'NE',
        codeNumber: 227,
        description: 'Niger',
      },
      {
        code: 'NG',
        codeNumber: 234,
        description: 'Nigeria',
      },
      {
        code: 'NU',
        codeNumber: 683,
        description: 'Niue Island',
      },
      {
        code: 'NF',
        codeNumber: 672,
        description: 'Norfolk Island',
      },
      {
        code: 'NO',
        codeNumber: 47,
        description: 'Norway',
      },
      {
        code: 'OM',
        codeNumber: 968,
        description: 'Oman',
      },
      {
        code: 'PC',
        codeNumber: 0,
        description: 'Pacific Island Trust Territory',
      },
      {
        code: 'PK',
        codeNumber: 92,
        description: 'Pakistan',
      },
      {
        code: 'PW',
        codeNumber: 680,
        description: 'Palau',
      },
      {
        code: 'PB',
        codeNumber: 970,
        description: 'Palestine',
      },
      {
        code: 'PA',
        codeNumber: 507,
        description: 'Panama',
      },
      {
        code: 'PZ',
        codeNumber: 0,
        description: 'Panama Canal Zone',
      },
      {
        code: 'PG',
        codeNumber: 675,
        description: 'Papua New Guinea',
      },
      {
        code: 'PY',
        codeNumber: 595,
        description: 'Paraguay',
      },
      {
        code: 'PE',
        codeNumber: 51,
        description: 'Peru',
      },
      {
        code: 'PH',
        codeNumber: 63,
        description: 'Philippines',
      },
      {
        code: 'PN',
        codeNumber: 64,
        description: 'Pitcairn Island',
      },
      {
        code: 'PL',
        codeNumber: 48,
        description: 'Poland',
      },
      {
        code: 'PT',
        codeNumber: 351,
        description: 'Portugal',
      },
      {
        code: 'PR',
        codeNumber: 787,
        description: 'Puerto Rico',
      },
      {
        code: 'QA',
        codeNumber: 974,
        description: 'Qatar',
      },
      {
        code: 'RE',
        codeNumber: 262,
        description: 'Reunion',
      },
      {
        code: 'RO',
        codeNumber: 40,
        description: 'Romania',
      },
      {
        code: 'RF',
        codeNumber: 7,
        description: 'Russia',
      },
      {
        code: 'RW',
        codeNumber: 250,
        description: 'Rwanda',
      },
      {
        code: 'WM',
        codeNumber: 685,
        description: 'Samoa',
      },
      {
        code: 'SM',
        codeNumber: 378,
        description: 'San Marino',
      },
      {
        code: 'ST',
        codeNumber: 239,
        description: 'Sao Tome & Principe',
      },
      {
        code: 'SA',
        codeNumber: 966,
        description: 'Saudi Arabia',
      },
      {
        code: 'SN',
        codeNumber: 221,
        description: 'Senegal',
      },
      {
        code: 'RS',
        codeNumber: 381,
        description: 'Serbia',
      },
      {
        code: 'SF',
        codeNumber: 381,
        description: 'Serbia/Montenegro',
      },
      {
        code: 'SC',
        codeNumber: 248,
        description: 'Seychelles',
      },
      {
        code: 'SL',
        codeNumber: 232,
        description: 'Sierra Leone',
      },
      {
        code: 'SK',
        codeNumber: 0,
        description: 'Slovak Republic',
      },
      {
        code: 'SI',
        codeNumber: 386,
        description: 'Slovenia',
      },
      {
        code: 'SB',
        codeNumber: 677,
        description: 'Solomon Islands',
      },
      {
        code: 'SO',
        codeNumber: 252,
        description: 'Somalia',
      },
      {
        code: 'ZA',
        codeNumber: 27,
        description: 'South Africa',
      },
      {
        code: 'ES',
        codeNumber: 34,
        description: 'Spain',
      },
      {
        code: 'LK',
        codeNumber: 94,
        description: 'Sri Lanka',
      },
      {
        code: 'SH',
        codeNumber: 290,
        description: 'St. Helena',
      },
      {
        code: 'KN',
        codeNumber: 1,
        description: 'St. Kitts-Nevis',
      },
      {
        code: 'LC',
        codeNumber: 1,
        description: 'St. Lucia',
      },
      {
        code: 'PM',
        codeNumber: 508,
        description: 'St. Pierre & Miquelon',
      },
      {
        code: 'VC',
        codeNumber: 1,
        description: 'St. Vincent',
      },
      {
        code: 'SD',
        codeNumber: 249,
        description: 'Sudan',
      },
      {
        code: 'SR',
        codeNumber: 597,
        description: 'Suriname',
      },
      {
        code: 'SZ',
        codeNumber: 268,
        description: 'Swaziland',
      },
      {
        code: 'SE',
        codeNumber: 46,
        description: 'Sweden',
      },
      {
        code: 'CH',
        codeNumber: 41,
        description: 'Switzerland',
      },
      {
        code: 'SY',
        codeNumber: 963,
        description: 'Syria',
      },
      {
        code: 'TW',
        codeNumber: 886,
        description: 'Taiwan',
      },
      {
        code: 'TI',
        codeNumber: 992,
        description: 'Tajikistan',
      },
      {
        code: 'TZ',
        codeNumber: 255,
        description: 'Tanzania',
      },
      {
        code: 'TH',
        codeNumber: 66,
        description: 'Thailand',
      },
      {
        code: 'TE',
        codeNumber: 0,
        description: 'Timor',
      },
      {
        code: 'TG',
        codeNumber: 228,
        description: 'Togo',
      },
      {
        code: 'TK',
        codeNumber: 690,
        description: 'Tokelau Islands',
      },
      {
        code: 'TO',
        codeNumber: 676,
        description: 'Tonga',
      },
      {
        code: 'TT',
        codeNumber: 1,
        description: 'Trinidad & Tobago',
      },
      {
        code: 'TN',
        codeNumber: 216,
        description: 'Tunisia',
      },
      {
        code: 'TR',
        codeNumber: 90,
        description: 'Turkey',
      },
      {
        code: 'TM',
        codeNumber: 993,
        description: 'Turkmenistan',
      },
      {
        code: 'TC',
        codeNumber: 1,
        description: 'Turks & Caicos Islands',
      },
      {
        code: 'TV',
        codeNumber: 688,
        description: 'Tuvalu',
      },
      {
        code: 'UG',
        codeNumber: 256,
        description: 'Uganda',
      },
      {
        code: 'UR',
        codeNumber: 380,
        description: 'Ukraine',
      },
      {
        code: 'AE',
        codeNumber: 971,
        description: 'United Arab Emirates',
      },
      {
        code: 'GB',
        codeNumber: 44,
        description: 'United Kingdom',
      },
      {
        code: 'US',
        codeNumber: 1,
        description: 'United States',
      },
      {
        code: 'HV',
        codeNumber: 0,
        description: 'Upper Volta',
      },
      {
        code: 'UY',
        codeNumber: 598,
        description: 'Uruguay',
      },
      {
        code: 'VI',
        codeNumber: 1,
        description: 'US Virgin Islands',
      },
      {
        code: 'UZ',
        codeNumber: 998,
        description: 'Uzbekistan',
      },
      {
        code: 'VU',
        codeNumber: 678,
        description: 'Vanuatu',
      },
      {
        code: 'VA',
        codeNumber: 39,
        description: 'Vatican City State',
      },
      {
        code: 'VE',
        codeNumber: 58,
        description: 'Venezuela',
      },
      {
        code: 'VN',
        codeNumber: 84,
        description: 'Vietnam',
      },
      {
        code: 'WK',
        codeNumber: 1,
        description: 'Wake Island',
      },
      {
        code: 'WF',
        codeNumber: 681,
        description: 'Wallis and Futuna',
      },
      {
        code: 'EH',
        codeNumber: 0,
        description: 'Western Sahara',
      },
      {
        code: 'YM',
        codeNumber: 967,
        description: 'Yemen',
      },
      {
        code: 'YU',
        codeNumber: 0,
        description: 'Yugoslavia',
      },
      {
        code: 'ZR',
        codeNumber: 243,
        description: 'Zaire',
      },
      {
        code: 'ZM',
        codeNumber: 260,
        description: 'Zambia',
      },
      {
        code: 'ZW',
        codeNumber: 263,
        description: 'Zimbabwe',
      },
    ]);
  });
  it('should have correct salary types', () => {
    expect(SALARY_TYPES).to.deep.equal([{id: 4, salaryType: 'Monthly'}, {id: 5, salaryType: 'Annual'}]);
  });
  it('should have correct company registration types', () => {
    expect(COMPANY_REGISTRATION_TYPES).to.deep.equal([
      {id: 1, registrationType: 'Registry of Company'},
      {id: 2, registrationType: 'Registry of Business'},
      {id: 3, registrationType: 'Other Unique Establishments (UENO)'},
      {id: 4, registrationType: 'Others - None of the Above'},
    ]);
  });
  it('should have correct subSchemes', () => {
    expect(SUB_SCHEMES).to.deep.equal([
      {
        endDate: '2017-12-31',
        id: 1,
        programme: 'WSQ Advanced Certificate in Industrial Design (PnT)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2015-01-26',
      },
      {
        endDate: '2019-02-04',
        id: 2,
        programme: 'PCP for Desktop/IT Support Administrators',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-17',
      },
      {
        endDate: '2019-02-04',
        id: 3,
        programme: 'PCP for ERP Specialist',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-17',
      },
      {
        endDate: '2019-02-04',
        id: 6,
        programme: 'PCP for ERP Specialist',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-17',
      },
      {
        endDate: '2019-05-31',
        id: 11,
        programme: 'PCP for International Trading Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-11-07',
      },
      {
        endDate: '2017-12-31',
        id: 12,
        programme: 'PCP for Biologics Manufacturing Sector',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2015-01-01',
      },
      {
        endDate: '2017-06-30',
        id: 14,
        programme: 'BOOST',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2014-07-01',
      },
      {
        endDate: '2019-02-21',
        id: 16,
        programme: 'Development and Apprenticeship (DNA) Programme - Pharmaceuticals Manufacturing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-22',
      },
      {
        endDate: '2019-02-21',
        id: 17,
        programme: 'Development and Apprenticeship (DNA) Programme - Biologics  Manufacturing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-22',
      },
      {
        endDate: '2018-05-31',
        id: 18,
        programme: 'PCP for Energy Management Sector (Project Manager)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-08-01',
      },
      {
        endDate: '2019-05-17',
        id: 21,
        programme: 'PCP for Retail Store Manager',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-05-10',
        id: 22,
        programme: 'PCP for MICE Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-12',
      },
      {
        endDate: '2017-12-30',
        id: 23,
        programme: 'PCP for Assistant Chef',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-01',
      },
      {
        endDate: '2017-12-30',
        id: 24,
        programme: 'PCP for Restaurant Manager',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-01',
      },
      {
        endDate: '2020-05-31',
        id: 25,
        programme: 'PCP for Public Transport Rail Sector (Station Manager/ Assistant Station Manager)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2015-11-07',
      },
      {
        endDate: '2018-08-31',
        id: 26,
        programme: 'Local BOOST (TP)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2015-09-01',
      },
      {
        endDate: '2019-02-21',
        id: 27,
        programme: 'Local BOOST (SP)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-22',
      },
      {
        endDate: '2019-06-30',
        id: 28,
        programme: 'PCP for Logistics (Officer)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-06-15',
      },
      {
        endDate: '2019-06-30',
        id: 29,
        programme: 'PCP for Logistics (Executive)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-06-15',
      },
      {
        endDate: '2019-05-31',
        id: 30,
        programme: 'PCP for Wafer Fab Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-01',
      },
      {
        endDate: '2019-05-31',
        id: 31,
        programme: 'PCP for Wafer Fab Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-01',
      },
      {
        endDate: '2019-05-31',
        id: 32,
        programme: 'PCP for A&T Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-01',
      },
      {
        endDate: '2019-05-31',
        id: 33,
        programme: 'PCP for A&T Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-01',
      },
      {
        endDate: '2018-05-30',
        id: 34,
        programme: 'PCP for Aircraft Maintenance (Avionics) Technician',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-09-22',
      },
      {
        endDate: '2018-05-30',
        id: 35,
        programme: 'PCP for Aircraft Maintenance (Mechanical) Technician',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-09-22',
      },
      {
        endDate: '2018-05-30',
        id: 36,
        programme: 'PCP for Engine Build Technician',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-09-22',
      },
      {
        endDate: '2018-05-30',
        id: 37,
        programme: 'PCP for Engine Repair and Overhaul Technician',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-09-22',
      },
      {
        endDate: '2018-12-17',
        id: 38,
        programme: 'PCP for Professional Executives (Hotel Industry)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-12-18',
      },
      {
        endDate: '2018-08-10',
        id: 39,
        programme: 'PCP for Pre-School Teachers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2015-08-01',
      },
      {
        endDate: '2020-05-31',
        id: 40,
        programme: 'PCP for Public Transport Rail Sector (Executive Engineer/ Assistant Engineer)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2019-05-01',
        id: 41,
        programme: 'PCP for Marine (Engineer)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-10-01',
      },
      {
        endDate: '2019-05-01',
        id: 42,
        programme: 'PCP for Marine (Assistant Engineer)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-10-01',
      },
      {
        endDate: '2019-05-01',
        id: 43,
        programme: 'PCP for Marine (Technician)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-10-01',
      },
      {
        endDate: '2019-09-01',
        id: 44,
        programme: 'PCP for Physiotherapists',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-19',
      },
      {
        endDate: '2019-09-01',
        id: 45,
        programme: 'PCP for Occupational Therapists',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-19',
      },
      {
        endDate: '2019-09-01',
        id: 46,
        programme: 'PCP for Diagnostic Radiographers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-19',
      },
      {
        endDate: '2020-06-01',
        id: 47,
        programme: 'PCP for Social Workers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-07-01',
      },
      {
        endDate: '2019-05-31',
        id: 48,
        programme: 'PCP for Manufacturing Associate',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-11-01',
      },
      {
        endDate: '2020-05-31',
        id: 49,
        programme: 'PCP for Manufacturing Professional',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-11-01',
      },
      {
        endDate: '2020-05-31',
        id: 50,
        programme: 'PCP for Technical Sales Engineer/Manager',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-11-01',
      },
      {
        endDate: '2019-05-31',
        id: 51,
        programme: 'PCP for Component OEM Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-05',
      },
      {
        endDate: '2019-05-31',
        id: 52,
        programme: 'PCP for Component OEM Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-05',
      },
      {
        endDate: '2019-05-31',
        id: 53,
        programme: 'PCP for Complex Equipment Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-05',
      },
      {
        endDate: '2019-05-31',
        id: 54,
        programme: 'PCP for Complex Equipment Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-05',
      },
      {
        endDate: '2019-05-31',
        id: 55,
        programme: 'PCP for Air Transport (Ground Operations Officer)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2018-11-30',
        id: 56,
        programme: 'PCP for System Integrator Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-09',
      },
      {
        endDate: '2018-11-30',
        id: 57,
        programme: 'PCP for System Integrator Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-09',
      },
      {
        endDate: '2018-05-31',
        id: 58,
        programme: 'PCP for Pharmaceuticals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-11-01',
      },
      {
        endDate: '2018-05-31',
        id: 59,
        programme: 'PCP for Chemicals Manufacturing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-07-11',
      },
      {
        endDate: '2020-05-31',
        id: 60,
        programme: 'PCP for Regional Operations Manager',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-24',
      },
      {
        endDate: '2020-05-31',
        id: 61,
        programme: 'PCP for Regional Technical Programme Manager',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-24',
      },
      {
        endDate: '2020-05-31',
        id: 62,
        programme: 'PCP for Professional Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2019-02-28',
        id: 63,
        programme: 'PCP for Infocomm Sales & Marketing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-01',
      },
      {
        endDate: '2019-05-31',
        id: 64,
        programme: 'PCP for Lift Technicians',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-01',
      },
      {
        endDate: '2019-06-28',
        id: 65,
        programme: 'PCP for Digital Marketing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-17',
      },
      {
        endDate: '2019-02-04',
        id: 66,
        programme: 'PCP for Infocomm and Sales',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-02-17',
      },
      {
        endDate: '2019-03-31',
        id: 67,
        programme: 'PCP for Care Coordinator Associates',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-12',
      },
      {
        endDate: '2018-05-31',
        id: 68,
        programme: 'PCP for Compliance Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-10-01',
      },
      {
        endDate: '2018-06-08',
        id: 69,
        programme: 'PCP for Hotel Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-25',
      },
      {
        endDate: '2018-06-11',
        id: 70,
        programme: 'PCP for Travel Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-03',
      },
      {
        endDate: '2020-05-31',
        id: 71,
        programme: 'PCP for Registered Nurses',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-05-31',
        id: 72,
        programme: 'PCP for Air Freight Officer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-01',
      },
      {
        endDate: '2019-05-31',
        id: 73,
        programme: 'PCP for Air Freight Executive',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-01',
      },
      {
        endDate: '2021-03-31',
        id: 74,
        programme: 'PCP for Digital Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-05-31',
        id: 75,
        programme: 'PCP for Associate Researcher',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-01',
      },
      {
        endDate: '2019-05-31',
        id: 76,
        programme: 'PCP for Aerospace Officers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-28',
      },
      {
        endDate: '2019-05-31',
        id: 77,
        programme: 'PCP for Aerospace Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-28',
      },
      {
        endDate: '2019-01-31',
        id: 78,
        programme: 'PCP for Banking Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-01-31',
        id: 79,
        programme: 'PCP for Financial Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-01',
      },
      {
        endDate: '2019-03-31',
        id: 80,
        programme: 'PCP for Global Ready Infrastructure Talent',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-12-31',
        id: 81,
        programme: 'PCP for Auxiliary Police Officer (APO)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-01',
      },
      {
        endDate: '2019-06-30',
        id: 82,
        programme: 'PCP for Apprentice Teachers (EIPIC/ Special Education)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-07-01',
      },
      {
        endDate: '2020-05-31',
        id: 83,
        programme: 'PCP for Enrolled Nurses',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2019-05-31',
        id: 84,
        programme: 'PCP for Airline Station Manager (Singapore Airlines)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-08-11',
      },
      {
        endDate: '2020-05-31',
        id: 85,
        programme: 'PCP for e-Commerce Supply Chain Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-08-14',
      },
      {
        endDate: '2019-03-01',
        id: 86,
        programme: 'PCP for Dental Surgery Assistants',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-03-01',
      },
      {
        endDate: '2019-12-31',
        id: 87,
        programme: 'PCP for Educational Therapists',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-01',
      },
      {
        endDate: '2019-03-31',
        id: 88,
        programme: 'PCP for GRIT',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-02-28',
        id: 89,
        programme: 'PCP for Game Writers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-23',
      },
      {
        endDate: '2018-10-24',
        id: 90,
        programme: 'PCP for Food Services Executives - Select Group',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-10-25',
      },
      {
        endDate: '2020-05-31',
        id: 91,
        programme: 'PCP for Electronics Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-01',
      },
      {
        endDate: '2020-05-31',
        id: 92,
        programme: 'PCP for Electronics Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-01',
      },
      {
        endDate: '2020-05-31',
        id: 93,
        programme: 'PCP for Advanced Manufacturing Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-21',
      },
      {
        endDate: '2020-05-31',
        id: 94,
        programme: 'PCP for Advanced Manufacturing Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-21',
      },
      {
        endDate: '2019-05-31',
        id: 95,
        programme: 'PCP for Public Transport Bus (Service Controller/ Assistant Service Controller)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-01',
      },
      {
        endDate: '2018-11-23',
        id: 96,
        programme: 'PCP for Food Services Executives - Super Bean',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-24',
      },
      {
        endDate: '2019-05-31',
        id: 97,
        programme: 'PCP for Medical Technology Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-10-01',
      },
      {
        endDate: '2019-05-31',
        id: 98,
        programme: 'PCP for Medical Technology Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-10-01',
      },
      {
        endDate: '2018-12-31',
        id: 99,
        programme: 'PCP for Professional Executives (Human Resource)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2019-08-31',
        id: 100,
        programme: 'PCP for Registered Nurses (Degree)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-19',
      },
      {
        endDate: '2019-05-31',
        id: 101,
        programme: 'PCP for Air Transport Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-02-02',
      },
      {
        endDate: '2020-05-31',
        id: 102,
        programme: 'PCP for Utilities Engineer/Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-01',
      },
      {
        endDate: '2019-11-30',
        id: 103,
        programme: 'PCP for Full Stack Software Developer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-05-25',
      },
      {
        endDate: '2020-05-30',
        id: 104,
        programme: 'PCP for BIM Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-07-06',
      },
      {
        endDate: '2019-05-31',
        id: 105,
        programme: 'AnT PCP for Artificial Intelligence Software Developer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-01',
      },
      {
        endDate: '2020-05-31',
        id: 106,
        programme: 'AnT PCP for Food Production Specialist',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-10',
      },
      {
        endDate: '2019-05-31',
        id: 107,
        programme: 'AnT PCP for Logistics (Executive)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-01',
      },
      {
        endDate: '2019-05-31',
        id: 108,
        programme: 'AnT PCP for Logistics (Officer)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-01',
      },
      {
        endDate: '2019-02-01',
        id: 109,
        programme: 'Local BOOST',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2015-09-01',
      },
      {
        endDate: '2019-05-31',
        id: 110,
        programme: 'PCP for Aerospace Executive',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-21',
      },
      {
        endDate: '2019-05-31',
        id: 111,
        programme: 'PCP for Aerospace Officer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-06-21',
      },
      {
        endDate: '2019-05-31',
        id: 112,
        programme: 'PCP for Airline Station Manager',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-05-02',
      },
      {
        endDate: '2020-05-01',
        id: 113,
        programme: 'PCP for Assistant Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-06-01',
      },
      {
        endDate: '2019-02-20',
        id: 114,
        programme: 'PCP for Biopharmaceutical Manufacturing Managers, Executives and Technicians',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-02-21',
      },
      {
        endDate: '2019-05-31',
        id: 115,
        programme: 'PCP for Bus Service Controller / Assistant Bus Service Controller',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-10-15',
      },
      {
        endDate: '2019-03-31',
        id: 116,
        programme: 'PCP for Care Coordinator/Patient Navigator Associates',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-04-01',
      },
      {
        endDate: '2019-03-31',
        id: 117,
        programme: 'PCP for Consultants - Ernst & Young',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-01',
      },
      {
        endDate: '2020-05-31',
        id: 118,
        programme: 'PCP for Consumer Banking Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-19',
      },
      {
        endDate: '2019-12-01',
        id: 119,
        programme: 'PCP for Data Science Professional',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2020-05-31',
        id: 120,
        programme: 'PCP for Digital Advertising Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-09-01',
      },
      {
        endDate: '2019-06-30',
        id: 121,
        programme: 'PCP for Early Intervention and Special Education Learning Facilitators',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-07-01',
      },
      {
        endDate: '2020-05-01',
        id: 122,
        programme: 'PCP for Executive Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-06-01',
      },
      {
        endDate: '2020-05-31',
        id: 123,
        programme: 'PCP for Financial Forensic Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-06-01',
      },
      {
        endDate: '2019-06-12',
        id: 124,
        programme: 'PCP for Food Services Executive - Kopi Roti and Oosterbay',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-06-13',
      },
      {
        endDate: '2019-12-31',
        id: 125,
        programme: 'PCP for Food Services Executives',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-08-21',
      },
      {
        endDate: '2019-07-31',
        id: 126,
        programme: 'PCP for Fund Management Executives (Dymon Asia)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-08-01',
      },
      {
        endDate: '2019-02-28',
        id: 127,
        programme: 'PCP for Furniture & Industrial Designers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-03-01',
      },
      {
        endDate: '2019-02-28',
        id: 128,
        programme: 'PCP for Graphic Designers',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-03-01',
      },
      {
        endDate: '2019-05-31',
        id: 129,
        programme: 'PCP for Ground Operations Officer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2019-06-28',
        id: 130,
        programme: 'PCP for Infocomm Sales and Marketing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-20',
      },
      {
        endDate: '2019-08-19',
        id: 131,
        programme: 'PCP for Intellectual Property Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-20',
      },
      {
        endDate: '2019-12-31',
        id: 132,
        programme: 'PCP for Internal Auditors',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-01-01',
      },
      {
        endDate: '2019-06-28',
        id: 133,
        programme: 'PCP for IT Desktop Support Executive',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-20',
      },
      {
        endDate: '2019-06-28',
        id: 134,
        programme: 'PCP for IT System Support Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-20',
      },
      {
        endDate: '2019-06-28',
        id: 135,
        programme: 'PCP for IT/Desktop and System Administrators',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-20',
      },
      {
        endDate: '2019-05-10',
        id: 136,
        programme: 'PCP for MICE Executives - Adrenalin Group Pte Ltd',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-05-11',
      },
      {
        endDate: '2019-05-10',
        id: 137,
        programme: 'PCP for MICE Executives - Aspen Event Planners Pte Ltd',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-05-11',
      },
      {
        endDate: '2019-05-31',
        id: 138,
        programme: 'PCP for MICE Executives - Kingsmen Creatives Ltd',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-06-01',
      },
      {
        endDate: '2020-01-01',
        id: 139,
        programme: 'PCP for Microsoft SQL Server Administrator / Developer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2020-01-01',
        id: 140,
        programme: 'PCP for Mobile Application Developer (Android & iOS)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2019-04-30',
        id: 141,
        programme: 'PCP for Network and Infrastructure Officers - Singtel',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-10-01',
      },
      {
        endDate: '2020-01-01',
        id: 142,
        programme: 'PCP for Network Engineer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2020-05-31',
        id: 143,
        programme: 'PCP for Operations (Banking) Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-19',
      },
      {
        endDate: '2020-05-31',
        id: 144,
        programme: 'PCP for Private Banking Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-19',
      },
      {
        endDate: '2019-03-01',
        id: 145,
        programme: 'PCP for Professional Executives - Hotel Sector (Amara Singapore)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-03-01',
      },
      {
        endDate: '2019-03-01',
        id: 146,
        programme: 'PCP for Professional Executives - Hotel Sector (Goodwood Park Hotel)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-09-01',
      },
      {
        endDate: '2019-05-20',
        id: 147,
        programme: 'PCP for Professional Executives - Hotel Sector (Grand Copthorne Waterfront)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-11-21',
      },
      {
        endDate: '2019-03-07',
        id: 148,
        programme: 'PCP for Professional Executives - Hotel Sector (Intercontinental Singapore Robertson Quay)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-09-08',
      },
      {
        endDate: '2019-06-03',
        id: 149,
        programme: 'PCP for Professional Executives - Hotel Sector (Intercontinental Singapore)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-06-04',
      },
      {
        endDate: '2020-05-31',
        id: 150,
        programme: 'PCP for Public Transport Rail Operations Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-10-01',
      },
      {
        endDate: '2021-03-31',
        id: 151,
        programme: 'PCP for Retail Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2016-05-01',
      },
      {
        endDate: '2019-07-31',
        id: 152,
        programme: 'PCP for Salesforce Platform Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-08-01',
      },
      {
        endDate: '2020-01-22',
        id: 153,
        programme: 'PCP for SAP HANA Consultant',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2020-01-01',
        id: 154,
        programme: 'PCP for Software Developer (.NET)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2020-05-31',
        id: 155,
        programme: 'PCP for South East Asia Ready Talents',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-08-01',
      },
      {
        endDate: '2020-05-30',
        id: 156,
        programme: 'PCP for Speech Therapists',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-01-01',
      },
      {
        endDate: '2020-01-01',
        id: 157,
        programme: 'PCP for System Administrator (Windows Server, Linux & MacOS)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2019-08-16',
        id: 158,
        programme: 'PCP for Tourism Executives (RWS)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-08-17',
      },
      {
        endDate: '2020-05-31',
        id: 159,
        programme: 'PCP for Trust Administration Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2018-04-19',
      },
      {
        endDate: '2020-01-01',
        id: 160,
        programme: 'PCP for Web Developer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2020-01-01',
        id: 161,
        programme: 'PCP for Web Developer (Linux, MySQL & PHP)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2017-02-01',
      },
      {
        endDate: '2020-05-31',
        id: 162,
        programme: 'PCP for Southeast Asia Ready Talents',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2020-05-31',
        id: 163,
        programme: 'PCP for Supply Chain Professionals',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-12-31',
        id: 164,
        programme: 'PCP for Data Analyst',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-06-28',
        id: 165,
        programme: 'PCP for Digital Marketing Specialist',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-06-28',
        id: 166,
        programme: 'PCP for Infocomm Sales & Marketing Specialist',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-07-31',
        id: 167,
        programme: 'PCP for Salesforce Sales Cloud Consultant',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-07-31',
        id: 168,
        programme: 'PCP for Salesforce Service Cloud Consultant',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-07-31',
        id: 169,
        programme: 'PCP for Salesforce Marketing Cloud Specialist',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2020-01-31',
        id: 170,
        programme: 'PCP for Microsoft SQL Server Administrator/Developer',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2020-01-31',
        id: 171,
        programme: 'PCP for Software Developer (Java)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2020-01-31',
        id: 172,
        programme: 'PCP for Network Security Analyst',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2020-01-31',
        id: 173,
        programme: 'PCP for Systems Administrator (Windows, Server, Linux, and MacOS)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-07-31',
        id: 174,
        programme: 'PCP for Consultants (Deloitte)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-05-31',
        id: 175,
        programme: 'PCP for Consultants (Ernst & Young)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2019-09-30',
        id: 176,
        programme: 'PCP for Consultants (KPMG)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-04-26',
      },
      {
        endDate: '2020-05-31',
        id: 177,
        programme: 'Attach and Train programme for Biologics Manufacturing (TP)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-05-31',
      },
      {
        endDate: '2020-03-31',
        id: 178,
        programme: 'PCP for Biopharmaceuticals Manufacturing',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-05-31',
      },
      {
        endDate: '2020-05-31',
        id: 179,
        programme: 'Attach and Train programme for Biologics Manufacturing (SP)',
        scheme: SCHEMES.find(({id}) => id === 2),
        startDate: '2019-05-31',
      },
    ]);
  });
});
