// data originating from MSF API

export const EMPLOYMENT_TYPES = [
  {ilpId: '02', ilpDescription: 'Temporary'},
  {ilpId: '03', ilpDescription: 'Contract Basis'},
  {ilpId: '05', ilpDescription: 'Part Time'},
  {ilpId: '06', ilpDescription: 'Freelance'},
  {ilpId: '07', ilpDescription: 'Permanent'},
  {ilpId: '08', ilpDescription: 'Full Time'},
  {ilpId: '09', ilpDescription: 'Flexi Work'},
  {ilpId: '10', ilpDescription: 'Internship'},
];

export const POSITION_LEVELS = [
  {jobLevelCode: 1, description: 'Senior Management'},
  {jobLevelCode: 2, description: 'Middle Management'},
  {jobLevelCode: 3, description: 'Manager'},
  {jobLevelCode: 6, description: 'Operational'},
  {jobLevelCode: 7, description: 'Professional'},
  {jobLevelCode: 8, description: 'Senior Executive'},
  {jobLevelCode: 9, description: 'Executive'},
  {jobLevelCode: 10, description: 'Junior Executive'},
  {jobLevelCode: 11, description: 'Non-executive'},
  {jobLevelCode: 12, description: 'Fresh / Entry level'},
];

export const JOB_CATEGORIES = [
  {
    jobCategoryId: 1,
    jobCategoryName: 'Accounting / Auditing / Taxation',
  },
  {
    jobCategoryId: 2,
    jobCategoryName: 'Admin / Secretarial',
  },
  {
    jobCategoryId: 3,
    jobCategoryName: 'Advertising / Media',
  },
  {
    jobCategoryId: 4,
    jobCategoryName: 'Architecture / Interior Design',
  },
  {
    jobCategoryId: 5,
    jobCategoryName: 'Banking and Finance',
  },
  {
    jobCategoryId: 6,
    jobCategoryName: 'Building and Construction',
  },
  {
    jobCategoryId: 7,
    jobCategoryName: 'Consulting',
  },
  {
    jobCategoryId: 8,
    jobCategoryName: 'Customer Service',
  },
  {
    jobCategoryId: 9,
    jobCategoryName: 'Design',
  },
  {
    jobCategoryId: 10,
    jobCategoryName: 'Education and Training',
  },
  {
    jobCategoryId: 11,
    jobCategoryName: 'Engineering',
  },
  {
    jobCategoryId: 12,
    jobCategoryName: 'Entertainment',
  },
  {
    jobCategoryId: 13,
    jobCategoryName: 'Environment / Health',
  },
  {
    jobCategoryId: 14,
    jobCategoryName: 'Events / Promotions',
  },
  {
    jobCategoryId: 15,
    jobCategoryName: 'F&B',
  },
  {
    jobCategoryId: 16,
    jobCategoryName: 'General Management',
  },
  {
    jobCategoryId: 17,
    jobCategoryName: 'General Work',
  },
  {
    jobCategoryId: 18,
    jobCategoryName: 'Healthcare / Pharmaceutical',
  },
  {
    jobCategoryId: 19,
    jobCategoryName: 'Hospitality',
  },
  {
    jobCategoryId: 20,
    jobCategoryName: 'Human Resources',
  },
  {
    jobCategoryId: 21,
    jobCategoryName: 'Information Technology',
  },
  {
    jobCategoryId: 22,
    jobCategoryName: 'Insurance',
  },
  {
    jobCategoryId: 23,
    jobCategoryName: 'Legal',
  },
  {
    jobCategoryId: 24,
    jobCategoryName: 'Logistics / Supply Chain',
  },
  {
    jobCategoryId: 25,
    jobCategoryName: 'Manufacturing',
  },
  {
    jobCategoryId: 26,
    jobCategoryName: 'Marketing / Public Relations',
  },
  {
    jobCategoryId: 27,
    jobCategoryName: 'Medical / Therapy Services',
  },
  {
    jobCategoryId: 28,
    jobCategoryName: 'Personal Care / Beauty',
  },
  {
    jobCategoryId: 29,
    jobCategoryName: 'Professional Services',
  },
  {
    jobCategoryId: 30,
    jobCategoryName: 'Public / Civil Service',
  },
  {
    jobCategoryId: 31,
    jobCategoryName: 'Purchasing / Merchandising',
  },
  {
    jobCategoryId: 32,
    jobCategoryName: 'Real Estate / Property Management',
  },
  {
    jobCategoryId: 33,
    jobCategoryName: 'Repair and Maintenance',
  },
  {
    jobCategoryId: 34,
    jobCategoryName: 'Risk Management',
  },
  {
    jobCategoryId: 35,
    jobCategoryName: 'Sales / Retail',
  },
  {
    jobCategoryId: 36,
    jobCategoryName: 'Sciences / Laboratory / R&D',
  },
  {
    jobCategoryId: 37,
    jobCategoryName: 'Security and Investigation',
  },
  {
    jobCategoryId: 38,
    jobCategoryName: 'Social Services',
  },
  {
    jobCategoryId: 39,
    jobCategoryName: 'Telecommunications',
  },
  {
    jobCategoryId: 40,
    jobCategoryName: 'Travel / Tourism',
  },
  {
    jobCategoryId: 41,
    jobCategoryName: 'Others',
  },
];

export const SCHEMES = [
  {id: '01', programme: 'CSP'},
  {id: '05', programme: 'PCP'},
  {id: '02', programme: 'P-Max'},
  {id: '06', programme: 'Career Trial'},
  {id: '07', programme: 'SGUnited Traineeships'},
];

export const JOB_STATUSES = [
  {id: 1, status: 'Closed'},
  {id: 2, status: 'Draft'},
  {id: 3, status: 'Open'},
  {id: 4, status: 'Re-open'},
];

export const DISTRICTS = [
  {
    district: 1,
    isDeleted: false,
    location: 'D01 Cecil, Marina, People’s Park, Raffles Place',
    sector: '01, 02, 03, 04, 05, 06',
  },
  {
    district: 2,
    isDeleted: false,
    location: 'D02 Anson, Tanjong Pagar',
    sector: '07, 08',
  },
  {
    district: 3,
    isDeleted: false,
    location: 'D03 Queenstown, Tiong Bahru',
    sector: '14,15, 16',
  },
  {
    district: 4,
    isDeleted: false,
    location: 'D04 Harbourfront,Telok Blangah, Sentosa Island',
    sector: '09, 10',
  },
  {
    district: 5,
    isDeleted: false,
    location: 'D05 Clementi New Town, Hong Leong Garden, Pasir Panjang',
    sector: '11, 12, 13',
  },
  {
    district: 6,
    isDeleted: false,
    location: 'D06 Beach Road, High Street',
    sector: '17',
  },
  {
    district: 7,
    isDeleted: false,
    location: 'D07 Golden Mile, Middle Road',
    sector: '18, 19',
  },
  {
    district: 8,
    isDeleted: false,
    location: 'D08 Little India',
    sector: '20, 21',
  },
  {
    district: 9,
    isDeleted: false,
    location: 'D09 Cairnhill, Orchard, River Valley',
    sector: '22, 23',
  },
  {
    district: 10,
    isDeleted: false,
    location: 'D10 Ardmore, Bukit Timah, Holland Road, Tanglin',
    sector: '24, 25, 26, 27',
  },
  {
    district: 11,
    isDeleted: false,
    location: 'D11 Novena, Thomson, Watten Estate',
    sector: '28, 29, 30',
  },
  {
    district: 12,
    isDeleted: false,
    location: 'D12 Balestier, Serangoon, Toa Payoh',
    sector: '31, 32, 33',
  },
  {
    district: 13,
    isDeleted: false,
    location: 'D13 Macpherson, Braddell',
    sector: '34, 35, 36, 37',
  },
  {
    district: 14,
    isDeleted: false,
    location: 'D14 Geylang, Eunos',
    sector: '38, 39, 40, 41',
  },
  {
    district: 15,
    isDeleted: false,
    location: 'D15 Katong, Joo Chiat, Amber Road',
    sector: '42, 43, 44, 45',
  },
  {
    district: 16,
    isDeleted: false,
    location: 'D16 Upper East Coast, Bedok, Eastwood, Kew Drive',
    sector: '46, 47, 48',
  },
  {
    district: 17,
    isDeleted: false,
    location: 'D17 Loyang, Changi',
    sector: '49, 50, 81, 91',
  },
  {
    district: 18,
    isDeleted: false,
    location: 'D18 Tampines, Pasir Ris',
    sector: '51, 52',
  },
  {
    district: 19,
    isDeleted: false,
    location: 'D19 Serangoon Garden, Hougang, Sengkang, Punggol',
    sector: '53, 54, 55, 82',
  },
  {
    district: 20,
    isDeleted: false,
    location: 'D20 Bishan, Ang Mo Kio',
    sector: '56, 57',
  },
  {
    district: 21,
    isDeleted: false,
    location: 'D21 Upper Bukit Timah, Clementi Park, Ulu Pandan',
    sector: '58, 59',
  },
  {
    district: 22,
    isDeleted: false,
    location: 'D22 Jurong, Jurong Island, Tuas',
    sector: '60, 61, 62, 63, 64',
  },
  {
    district: 23,
    isDeleted: false,
    location: 'D23 Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang',
    sector: '65, 66, 67, 68',
  },
  {
    district: 24,
    isDeleted: false,
    location: 'D24 Lim Chu Kang, Tengah',
    sector: '69, 70, 71',
  },
  {
    district: 25,
    isDeleted: false,
    location: 'D25 Kranji, Woodgrove, Woodlands',
    sector: '72, 73',
  },
  {
    district: 26,
    isDeleted: false,
    location: 'D26 Upper Thomson, Springleaf',
    sector: '77, 78',
  },
  {
    district: 27,
    isDeleted: false,
    location: 'D27 Yishun, Sembawang',
    sector: '75, 76',
  },
  {
    district: 28,
    isDeleted: false,
    location: 'D28 Seletar',
    sector: '79, 80',
  },
  {
    district: 998,
    isDeleted: false,
    location: 'Islandwide',
    sector: '9999',
  },
  {
    district: 999,
    isDeleted: false,
    location: 'Overseas',
    sector: 'XX',
  },
];

export const COUNTRIES = [
  {
    countryCode: 'SG',
    countryCodeNumber: 65,
    description: 'Singapore',
    isDeleted: false,
  },
  {
    countryCode: 'AF',
    countryCodeNumber: 93,
    description: 'Afghanistan',
    isDeleted: false,
  },
  {
    countryCode: 'AL',
    countryCodeNumber: 355,
    description: 'Albania',
    isDeleted: false,
  },
  {
    countryCode: 'DZ',
    countryCodeNumber: 213,
    description: 'Algeria',
    isDeleted: false,
  },
  {
    countryCode: 'AS',
    countryCodeNumber: 1,
    description: 'American Samoa',
    isDeleted: false,
  },
  {
    countryCode: 'AD',
    countryCodeNumber: 376,
    description: 'Andorra',
    isDeleted: false,
  },
  {
    countryCode: 'AO',
    countryCodeNumber: 244,
    description: 'Angola',
    isDeleted: false,
  },
  {
    countryCode: 'AI',
    countryCodeNumber: 0,
    description: 'Anguilla',
    isDeleted: false,
  },
  {
    countryCode: 'AG',
    countryCodeNumber: 1,
    description: 'Antigua',
    isDeleted: false,
  },
  {
    countryCode: 'AR',
    countryCodeNumber: 54,
    description: 'Argentina',
    isDeleted: false,
  },
  {
    countryCode: 'AM',
    countryCodeNumber: 374,
    description: 'Armenia',
    isDeleted: false,
  },
  {
    countryCode: 'AB',
    countryCodeNumber: 297,
    description: 'Aruba',
    isDeleted: false,
  },
  {
    countryCode: 'AU',
    countryCodeNumber: 61,
    description: 'Australia',
    isDeleted: false,
  },
  {
    countryCode: 'AT',
    countryCodeNumber: 43,
    description: 'Austria',
    isDeleted: false,
  },
  {
    countryCode: 'AZ',
    countryCodeNumber: 994,
    description: 'Azerbaijan',
    isDeleted: false,
  },
  {
    countryCode: 'BS',
    countryCodeNumber: 1,
    description: 'Bahamas',
    isDeleted: false,
  },
  {
    countryCode: 'BH',
    countryCodeNumber: 973,
    description: 'Bahrain',
    isDeleted: false,
  },
  {
    countryCode: 'BD',
    countryCodeNumber: 880,
    description: 'Bangladesh',
    isDeleted: false,
  },
  {
    countryCode: 'BB',
    countryCodeNumber: 1,
    description: 'Barbados',
    isDeleted: false,
  },
  {
    countryCode: 'BL',
    countryCodeNumber: 375,
    description: 'Belarus',
    isDeleted: false,
  },
  {
    countryCode: 'BE',
    countryCodeNumber: 32,
    description: 'Belgium',
    isDeleted: false,
  },
  {
    countryCode: 'BZ',
    countryCodeNumber: 501,
    description: 'Belize',
    isDeleted: false,
  },
  {
    countryCode: 'BJ',
    countryCodeNumber: 229,
    description: 'Benin',
    isDeleted: false,
  },
  {
    countryCode: 'BM',
    countryCodeNumber: 1,
    description: 'Bermuda',
    isDeleted: false,
  },
  {
    countryCode: 'BT',
    countryCodeNumber: 975,
    description: 'Bhutan',
    isDeleted: false,
  },
  {
    countryCode: 'BO',
    countryCodeNumber: 591,
    description: 'Bolivia',
    isDeleted: false,
  },
  {
    countryCode: 'BA',
    countryCodeNumber: 387,
    description: 'Bosnia-Herzegovina',
    isDeleted: false,
  },
  {
    countryCode: 'BW',
    countryCodeNumber: 267,
    description: 'Botswana',
    isDeleted: false,
  },
  {
    countryCode: 'BR',
    countryCodeNumber: 55,
    description: 'Brazil',
    isDeleted: false,
  },
  {
    countryCode: 'BQ',
    countryCodeNumber: 0,
    description: 'British Antarctic Territory',
    isDeleted: false,
  },
  {
    countryCode: 'IO',
    countryCodeNumber: 0,
    description: 'British Indian Ocean Territory',
    isDeleted: false,
  },
  {
    countryCode: 'VG',
    countryCodeNumber: 1,
    description: 'British Virgin Islands',
    isDeleted: false,
  },
  {
    countryCode: 'BN',
    countryCodeNumber: 673,
    description: 'Brunei',
    isDeleted: false,
  },
  {
    countryCode: 'BG',
    countryCodeNumber: 359,
    description: 'Bulgaria',
    isDeleted: false,
  },
  {
    countryCode: 'BF',
    countryCodeNumber: 226,
    description: 'Burkina Faso',
    isDeleted: false,
  },
  {
    countryCode: 'BI',
    countryCodeNumber: 257,
    description: 'Burundi',
    isDeleted: false,
  },
  {
    countryCode: 'KA',
    countryCodeNumber: 855,
    description: 'Cambodia',
    isDeleted: false,
  },
  {
    countryCode: 'CM',
    countryCodeNumber: 237,
    description: 'Cameroon',
    isDeleted: false,
  },
  {
    countryCode: 'CA',
    countryCodeNumber: 1,
    description: 'Canada',
    isDeleted: false,
  },
  {
    countryCode: 'CT',
    countryCodeNumber: 0,
    description: 'Canton & Enderbury Islands',
    isDeleted: false,
  },
  {
    countryCode: 'CV',
    countryCodeNumber: 238,
    description: 'Cape Verde',
    isDeleted: false,
  },
  {
    countryCode: 'KY',
    countryCodeNumber: 1,
    description: 'Cayman Islands',
    isDeleted: false,
  },
  {
    countryCode: 'CF',
    countryCodeNumber: 236,
    description: 'Central African Republic',
    isDeleted: false,
  },
  {
    countryCode: 'TD',
    countryCodeNumber: 235,
    description: 'Chad',
    isDeleted: false,
  },
  {
    countryCode: 'CD',
    countryCodeNumber: 0,
    description: 'Channel Islands',
    isDeleted: false,
  },
  {
    countryCode: 'CL',
    countryCodeNumber: 56,
    description: 'Chile',
    isDeleted: false,
  },
  {
    countryCode: 'CN',
    countryCodeNumber: 86,
    description: 'China',
    isDeleted: false,
  },
  {
    countryCode: 'CX',
    countryCodeNumber: 0,
    description: 'Christmas Island',
    isDeleted: false,
  },
  {
    countryCode: 'CC',
    countryCodeNumber: 0,
    description: 'Cocos Keeling Island',
    isDeleted: false,
  },
  {
    countryCode: 'CO',
    countryCodeNumber: 57,
    description: 'Colombia',
    isDeleted: false,
  },
  {
    countryCode: 'KM',
    countryCodeNumber: 269,
    description: 'Comoros',
    isDeleted: false,
  },
  {
    countryCode: 'CG',
    countryCodeNumber: 242,
    description: 'Congo',
    isDeleted: false,
  },
  {
    countryCode: 'CK',
    countryCodeNumber: 682,
    description: 'Cook Islands',
    isDeleted: false,
  },
  {
    countryCode: 'CR',
    countryCodeNumber: 506,
    description: 'Costa Rica',
    isDeleted: false,
  },
  {
    countryCode: 'CB',
    countryCodeNumber: 385,
    description: 'Croatia',
    isDeleted: false,
  },
  {
    countryCode: 'CU',
    countryCodeNumber: 53,
    description: 'Cuba',
    isDeleted: false,
  },
  {
    countryCode: 'CY',
    countryCodeNumber: 357,
    description: 'Cyprus',
    isDeleted: false,
  },
  {
    countryCode: 'CZ',
    countryCodeNumber: 420,
    description: 'Czech Republic',
    isDeleted: false,
  },
  {
    countryCode: 'DK',
    countryCodeNumber: 45,
    description: 'Denmark',
    isDeleted: false,
  },
  {
    countryCode: 'DJ',
    countryCodeNumber: 253,
    description: 'Djibouti',
    isDeleted: false,
  },
  {
    countryCode: 'DM',
    countryCodeNumber: 1,
    description: 'Dominica',
    isDeleted: false,
  },
  {
    countryCode: 'DO',
    countryCodeNumber: 1,
    description: 'Dominican Republic',
    isDeleted: false,
  },
  {
    countryCode: 'TP',
    countryCodeNumber: 0,
    description: 'East Timor',
    isDeleted: false,
  },
  {
    countryCode: 'EC',
    countryCodeNumber: 593,
    description: 'Ecuador',
    isDeleted: false,
  },
  {
    countryCode: 'EG',
    countryCodeNumber: 20,
    description: 'Egypt',
    isDeleted: false,
  },
  {
    countryCode: 'SV',
    countryCodeNumber: 503,
    description: 'El Salvador',
    isDeleted: false,
  },
  {
    countryCode: 'GQ',
    countryCodeNumber: 240,
    description: 'Equatorial Guinea',
    isDeleted: false,
  },
  {
    countryCode: 'ER',
    countryCodeNumber: 291,
    description: 'Eritrea',
    isDeleted: false,
  },
  {
    countryCode: 'EN',
    countryCodeNumber: 372,
    description: 'Estonia',
    isDeleted: false,
  },
  {
    countryCode: 'ET',
    countryCodeNumber: 251,
    description: 'Ethiopia',
    isDeleted: false,
  },
  {
    countryCode: 'FO',
    countryCodeNumber: 298,
    description: 'Faeroe Islands',
    isDeleted: false,
  },
  {
    countryCode: 'FK',
    countryCodeNumber: 500,
    description: 'Falkland Islands',
    isDeleted: false,
  },
  {
    countryCode: 'FJ',
    countryCodeNumber: 679,
    description: 'Fiji',
    isDeleted: false,
  },
  {
    countryCode: 'FI',
    countryCodeNumber: 358,
    description: 'Finland',
    isDeleted: false,
  },
  {
    countryCode: 'FR',
    countryCodeNumber: 33,
    description: 'France',
    isDeleted: false,
  },
  {
    countryCode: 'GF',
    countryCodeNumber: 594,
    description: 'French Guiana',
    isDeleted: false,
  },
  {
    countryCode: 'PF',
    countryCodeNumber: 689,
    description: 'French Polynesia',
    isDeleted: false,
  },
  {
    countryCode: 'FQ',
    countryCodeNumber: 298,
    description: 'French Southern & Antarctic Territories',
    isDeleted: false,
  },
  {
    countryCode: 'GA',
    countryCodeNumber: 241,
    description: 'Gabon',
    isDeleted: false,
  },
  {
    countryCode: 'GM',
    countryCodeNumber: 220,
    description: 'Gambia',
    isDeleted: false,
  },
  {
    countryCode: 'GZ',
    countryCodeNumber: 0,
    description: 'Gaza',
    isDeleted: false,
  },
  {
    countryCode: 'GO',
    countryCodeNumber: 995,
    description: 'Georgia',
    isDeleted: false,
  },
  {
    countryCode: 'DG',
    countryCodeNumber: 49,
    description: 'Germany',
    isDeleted: false,
  },
  {
    countryCode: 'GH',
    countryCodeNumber: 233,
    description: 'Ghana',
    isDeleted: false,
  },
  {
    countryCode: 'GI',
    countryCodeNumber: 350,
    description: 'Gibraltar',
    isDeleted: false,
  },
  {
    countryCode: 'GR',
    countryCodeNumber: 30,
    description: 'Greece',
    isDeleted: false,
  },
  {
    countryCode: 'GL',
    countryCodeNumber: 299,
    description: 'Greenland',
    isDeleted: false,
  },
  {
    countryCode: 'GD',
    countryCodeNumber: 1,
    description: 'Grenada',
    isDeleted: false,
  },
  {
    countryCode: 'GP',
    countryCodeNumber: 590,
    description: 'Guadeloupe',
    isDeleted: false,
  },
  {
    countryCode: 'GU',
    countryCodeNumber: 1,
    description: 'Guam',
    isDeleted: false,
  },
  {
    countryCode: 'GT',
    countryCodeNumber: 502,
    description: 'Guatemala',
    isDeleted: false,
  },
  {
    countryCode: 'GK',
    countryCodeNumber: 0,
    description: 'Guernsey',
    isDeleted: false,
  },
  {
    countryCode: 'GN',
    countryCodeNumber: 224,
    description: 'Guinea',
    isDeleted: false,
  },
  {
    countryCode: 'GW',
    countryCodeNumber: 245,
    description: 'Guinea-Bissau',
    isDeleted: false,
  },
  {
    countryCode: 'GY',
    countryCodeNumber: 592,
    description: 'Guyana',
    isDeleted: false,
  },
  {
    countryCode: 'HT',
    countryCodeNumber: 509,
    description: 'Haiti',
    isDeleted: false,
  },
  {
    countryCode: 'HM',
    countryCodeNumber: 0,
    description: 'Heard Island & McDonald Islands',
    isDeleted: false,
  },
  {
    countryCode: 'HN',
    countryCodeNumber: 504,
    description: 'Honduras',
    isDeleted: false,
  },
  {
    countryCode: 'HK',
    countryCodeNumber: 0,
    description: 'Hong Kong',
    isDeleted: false,
  },
  {
    countryCode: 'HS',
    countryCodeNumber: 852,
    description: 'Hong Kong SAR',
    isDeleted: false,
  },
  {
    countryCode: 'HU',
    countryCodeNumber: 36,
    description: 'Hungary',
    isDeleted: false,
  },
  {
    countryCode: 'IS',
    countryCodeNumber: 354,
    description: 'Iceland',
    isDeleted: false,
  },
  {
    countryCode: 'IN',
    countryCodeNumber: 91,
    description: 'India',
    isDeleted: false,
  },
  {
    countryCode: 'ID',
    countryCodeNumber: 62,
    description: 'Indonesia',
    isDeleted: false,
  },
  {
    countryCode: 'IR',
    countryCodeNumber: 98,
    description: 'Iran',
    isDeleted: false,
  },
  {
    countryCode: 'IQ',
    countryCodeNumber: 964,
    description: 'Iraq',
    isDeleted: false,
  },
  {
    countryCode: 'IE',
    countryCodeNumber: 353,
    description: 'Ireland',
    isDeleted: false,
  },
  {
    countryCode: 'MM',
    countryCodeNumber: 0,
    description: 'Isle Of Man',
    isDeleted: false,
  },
  {
    countryCode: 'IL',
    countryCodeNumber: 972,
    description: 'Israel',
    isDeleted: false,
  },
  {
    countryCode: 'IT',
    countryCodeNumber: 39,
    description: 'Italy',
    isDeleted: false,
  },
  {
    countryCode: 'CI',
    countryCodeNumber: 225,
    description: 'Ivory Coast',
    isDeleted: false,
  },
  {
    countryCode: 'JM',
    countryCodeNumber: 0,
    description: 'Jamaica',
    isDeleted: false,
  },
  {
    countryCode: 'JP',
    countryCodeNumber: 962,
    description: 'Japan',
    isDeleted: false,
  },
  {
    countryCode: 'JT',
    countryCodeNumber: 81,
    description: 'Johnston Island',
    isDeleted: false,
  },
  {
    countryCode: 'JO',
    countryCodeNumber: 1,
    description: 'Jordan',
    isDeleted: false,
  },
  {
    countryCode: 'KZ',
    countryCodeNumber: 7,
    description: 'Kazakhstan',
    isDeleted: false,
  },
  {
    countryCode: 'KE',
    countryCodeNumber: 254,
    description: 'Kenya',
    isDeleted: false,
  },
  {
    countryCode: 'KG',
    countryCodeNumber: 0,
    description: 'Kirghizia',
    isDeleted: false,
  },
  {
    countryCode: 'KI',
    countryCodeNumber: 686,
    description: 'Kiribati',
    isDeleted: false,
  },
  {
    countryCode: 'KP',
    countryCodeNumber: 82,
    description: 'Korea, North',
    isDeleted: false,
  },
  {
    countryCode: 'KR',
    countryCodeNumber: 856,
    description: 'Korea, South',
    isDeleted: false,
  },
  {
    countryCode: 'KV',
    countryCodeNumber: 0,
    description: 'Kosovo',
    isDeleted: false,
  },
  {
    countryCode: 'KW',
    countryCodeNumber: 965,
    description: 'Kuwait',
    isDeleted: false,
  },
  {
    countryCode: 'KS',
    countryCodeNumber: 996,
    description: 'Kyrgyzstan',
    isDeleted: false,
  },
  {
    countryCode: 'LA',
    countryCodeNumber: 218,
    description: 'Laos',
    isDeleted: false,
  },
  {
    countryCode: 'LV',
    countryCodeNumber: 371,
    description: 'Latvia',
    isDeleted: false,
  },
  {
    countryCode: 'LB',
    countryCodeNumber: 961,
    description: 'Lebanon',
    isDeleted: false,
  },
  {
    countryCode: 'LS',
    countryCodeNumber: 266,
    description: 'Lesotho',
    isDeleted: false,
  },
  {
    countryCode: 'LR',
    countryCodeNumber: 231,
    description: 'Liberia',
    isDeleted: false,
  },
  {
    countryCode: 'LY',
    countryCodeNumber: 850,
    description: 'Libya',
    isDeleted: false,
  },
  {
    countryCode: 'LI',
    countryCodeNumber: 423,
    description: 'Liechtenstein',
    isDeleted: false,
  },
  {
    countryCode: 'LH',
    countryCodeNumber: 370,
    description: 'Lithuania',
    isDeleted: false,
  },
  {
    countryCode: 'LU',
    countryCodeNumber: 352,
    description: 'Luxembourg',
    isDeleted: false,
  },
  {
    countryCode: 'MO',
    countryCodeNumber: 0,
    description: 'Macao',
    isDeleted: false,
  },
  {
    countryCode: 'MF',
    countryCodeNumber: 853,
    description: 'Macau SAR',
    isDeleted: false,
  },
  {
    countryCode: 'MB',
    countryCodeNumber: 0,
    description: 'Macedonia',
    isDeleted: false,
  },
  {
    countryCode: 'MG',
    countryCodeNumber: 261,
    description: 'Madagascar',
    isDeleted: false,
  },
  {
    countryCode: 'MW',
    countryCodeNumber: 265,
    description: 'Malawi',
    isDeleted: false,
  },
  {
    countryCode: 'MY',
    countryCodeNumber: 60,
    description: 'Malaysia',
    isDeleted: false,
  },
  {
    countryCode: 'MV',
    countryCodeNumber: 960,
    description: 'Maldives',
    isDeleted: false,
  },
  {
    countryCode: 'ML',
    countryCodeNumber: 223,
    description: 'Mali',
    isDeleted: false,
  },
  {
    countryCode: 'MT',
    countryCodeNumber: 356,
    description: 'Malta',
    isDeleted: false,
  },
  {
    countryCode: 'MH',
    countryCodeNumber: 692,
    description: 'Marshall Islands',
    isDeleted: false,
  },
  {
    countryCode: 'MQ',
    countryCodeNumber: 596,
    description: 'Martinique',
    isDeleted: false,
  },
  {
    countryCode: 'MR',
    countryCodeNumber: 222,
    description: 'Mauritania',
    isDeleted: false,
  },
  {
    countryCode: 'MU',
    countryCodeNumber: 230,
    description: 'Mauritius',
    isDeleted: false,
  },
  {
    countryCode: 'ME',
    countryCodeNumber: 0,
    description: 'Mayotte',
    isDeleted: false,
  },
  {
    countryCode: 'MX',
    countryCodeNumber: 52,
    description: 'Mexico',
    isDeleted: false,
  },
  {
    countryCode: 'MI',
    countryCodeNumber: 1,
    description: 'Midway Islands',
    isDeleted: false,
  },
  {
    countryCode: 'MD',
    countryCodeNumber: 373,
    description: 'Moldova',
    isDeleted: false,
  },
  {
    countryCode: 'MC',
    countryCodeNumber: 377,
    description: 'Monaco',
    isDeleted: false,
  },
  {
    countryCode: 'MN',
    countryCodeNumber: 976,
    description: 'Mongolia',
    isDeleted: false,
  },
  {
    countryCode: 'MJ',
    countryCodeNumber: 382,
    description: 'Montenegro',
    isDeleted: false,
  },
  {
    countryCode: 'MS',
    countryCodeNumber: 1,
    description: 'Montserrat',
    isDeleted: false,
  },
  {
    countryCode: 'MA',
    countryCodeNumber: 212,
    description: 'Morocco',
    isDeleted: false,
  },
  {
    countryCode: 'MZ',
    countryCodeNumber: 258,
    description: 'Mozambique',
    isDeleted: false,
  },
  {
    countryCode: 'BU',
    countryCodeNumber: 0,
    description: 'Myanmar',
    isDeleted: false,
  },
  {
    countryCode: 'NA',
    countryCodeNumber: 264,
    description: 'Namibia',
    isDeleted: false,
  },
  {
    countryCode: 'NR',
    countryCodeNumber: 674,
    description: 'Nauru',
    isDeleted: false,
  },
  {
    countryCode: 'NP',
    countryCodeNumber: 977,
    description: 'Nepal',
    isDeleted: false,
  },
  {
    countryCode: 'NL',
    countryCodeNumber: 31,
    description: 'Netherlands',
    isDeleted: false,
  },
  {
    countryCode: 'AN',
    countryCodeNumber: 599,
    description: 'Netherlands Antililles',
    isDeleted: false,
  },
  {
    countryCode: 'NC',
    countryCodeNumber: 687,
    description: 'New Caledonia',
    isDeleted: false,
  },
  {
    countryCode: 'NZ',
    countryCodeNumber: 64,
    description: 'New Zealand',
    isDeleted: false,
  },
  {
    countryCode: 'NI',
    countryCodeNumber: 505,
    description: 'Nicaragua',
    isDeleted: false,
  },
  {
    countryCode: 'NE',
    countryCodeNumber: 227,
    description: 'Niger',
    isDeleted: false,
  },
  {
    countryCode: 'NG',
    countryCodeNumber: 234,
    description: 'Nigeria',
    isDeleted: false,
  },
  {
    countryCode: 'NU',
    countryCodeNumber: 683,
    description: 'Niue Island',
    isDeleted: false,
  },
  {
    countryCode: 'NF',
    countryCodeNumber: 672,
    description: 'Norfolk Island',
    isDeleted: false,
  },
  {
    countryCode: 'NO',
    countryCodeNumber: 47,
    description: 'Norway',
    isDeleted: false,
  },
  {
    countryCode: 'OM',
    countryCodeNumber: 968,
    description: 'Oman',
    isDeleted: false,
  },
  {
    countryCode: 'PC',
    countryCodeNumber: 0,
    description: 'Pacific Island Trust Territory',
    isDeleted: false,
  },
  {
    countryCode: 'PK',
    countryCodeNumber: 92,
    description: 'Pakistan',
    isDeleted: false,
  },
  {
    countryCode: 'PW',
    countryCodeNumber: 680,
    description: 'Palau',
    isDeleted: false,
  },
  {
    countryCode: 'PB',
    countryCodeNumber: 0,
    description: 'Palestine',
    isDeleted: false,
  },
  {
    countryCode: 'PA',
    countryCodeNumber: 507,
    description: 'Panama',
    isDeleted: false,
  },
  {
    countryCode: 'PZ',
    countryCodeNumber: 0,
    description: 'Panama Canal Zone',
    isDeleted: false,
  },
  {
    countryCode: 'PG',
    countryCodeNumber: 675,
    description: 'Papua New Guinea',
    isDeleted: false,
  },
  {
    countryCode: 'PY',
    countryCodeNumber: 595,
    description: 'Paraguay',
    isDeleted: false,
  },
  {
    countryCode: 'PE',
    countryCodeNumber: 51,
    description: 'Peru',
    isDeleted: false,
  },
  {
    countryCode: 'PH',
    countryCodeNumber: 63,
    description: 'Philippines',
    isDeleted: false,
  },
  {
    countryCode: 'PN',
    countryCodeNumber: 0,
    description: 'Pitcairn Island',
    isDeleted: false,
  },
  {
    countryCode: 'PL',
    countryCodeNumber: 48,
    description: 'Poland',
    isDeleted: false,
  },
  {
    countryCode: 'PT',
    countryCodeNumber: 351,
    description: 'Portugal',
    isDeleted: false,
  },
  {
    countryCode: 'PR',
    countryCodeNumber: 787,
    description: 'Puerto Rico',
    isDeleted: false,
  },
  {
    countryCode: 'QA',
    countryCodeNumber: 974,
    description: 'Qatar',
    isDeleted: false,
  },
  {
    countryCode: 'RE',
    countryCodeNumber: 262,
    description: 'Reunion',
    isDeleted: false,
  },
  {
    countryCode: 'RO',
    countryCodeNumber: 40,
    description: 'Romania',
    isDeleted: false,
  },
  {
    countryCode: 'RF',
    countryCodeNumber: 0,
    description: 'Russia',
    isDeleted: false,
  },
  {
    countryCode: 'RW',
    countryCodeNumber: 250,
    description: 'Rwanda',
    isDeleted: false,
  },
  {
    countryCode: 'WM',
    countryCodeNumber: 685,
    description: 'Samoa',
    isDeleted: false,
  },
  {
    countryCode: 'SM',
    countryCodeNumber: 378,
    description: 'San Marino',
    isDeleted: false,
  },
  {
    countryCode: 'ST',
    countryCodeNumber: 239,
    description: 'Sao Tome & Principe',
    isDeleted: false,
  },
  {
    countryCode: 'SA',
    countryCodeNumber: 966,
    description: 'Saudi Arabia',
    isDeleted: false,
  },
  {
    countryCode: 'SN',
    countryCodeNumber: 221,
    description: 'Senegal',
    isDeleted: false,
  },
  {
    countryCode: 'RS',
    countryCodeNumber: 381,
    description: 'Serbia',
    isDeleted: false,
  },
  {
    countryCode: 'SF',
    countryCodeNumber: 381,
    description: 'Serbia/Montenegro',
    isDeleted: false,
  },
  {
    countryCode: 'SC',
    countryCodeNumber: 248,
    description: 'Seychelles',
    isDeleted: false,
  },
  {
    countryCode: 'SL',
    countryCodeNumber: 232,
    description: 'Sierra Leone',
    isDeleted: false,
  },
  {
    countryCode: 'SK',
    countryCodeNumber: 0,
    description: 'Slovak Republic',
    isDeleted: false,
  },
  {
    countryCode: 'SI',
    countryCodeNumber: 386,
    description: 'Slovenia',
    isDeleted: false,
  },
  {
    countryCode: 'SB',
    countryCodeNumber: 677,
    description: 'Solomon Islands',
    isDeleted: false,
  },
  {
    countryCode: 'SO',
    countryCodeNumber: 252,
    description: 'Somalia',
    isDeleted: false,
  },
  {
    countryCode: 'ZA',
    countryCodeNumber: 27,
    description: 'South Africa',
    isDeleted: false,
  },
  {
    countryCode: 'ES',
    countryCodeNumber: 34,
    description: 'Spain',
    isDeleted: false,
  },
  {
    countryCode: 'LK',
    countryCodeNumber: 94,
    description: 'Sri Lanka',
    isDeleted: false,
  },
  {
    countryCode: 'SH',
    countryCodeNumber: 290,
    description: 'St. Helena',
    isDeleted: false,
  },
  {
    countryCode: 'KN',
    countryCodeNumber: 1,
    description: 'St. Kitts-Nevis',
    isDeleted: false,
  },
  {
    countryCode: 'LC',
    countryCodeNumber: 1,
    description: 'St. Lucia',
    isDeleted: false,
  },
  {
    countryCode: 'PM',
    countryCodeNumber: 508,
    description: 'St. Pierre & Miquelon',
    isDeleted: false,
  },
  {
    countryCode: 'VC',
    countryCodeNumber: 1,
    description: 'St. Vincent',
    isDeleted: false,
  },
  {
    countryCode: 'SD',
    countryCodeNumber: 249,
    description: 'Sudan',
    isDeleted: false,
  },
  {
    countryCode: 'SR',
    countryCodeNumber: 597,
    description: 'Suriname',
    isDeleted: false,
  },
  {
    countryCode: 'SZ',
    countryCodeNumber: 268,
    description: 'Swaziland',
    isDeleted: false,
  },
  {
    countryCode: 'SE',
    countryCodeNumber: 46,
    description: 'Sweden',
    isDeleted: false,
  },
  {
    countryCode: 'CH',
    countryCodeNumber: 41,
    description: 'Switzerland',
    isDeleted: false,
  },
  {
    countryCode: 'SY',
    countryCodeNumber: 963,
    description: 'Syria',
    isDeleted: false,
  },
  {
    countryCode: 'TW',
    countryCodeNumber: 886,
    description: 'Taiwan',
    isDeleted: false,
  },
  {
    countryCode: 'TI',
    countryCodeNumber: 0,
    description: 'Tajikistan',
    isDeleted: false,
  },
  {
    countryCode: 'TZ',
    countryCodeNumber: 255,
    description: 'Tanzania',
    isDeleted: false,
  },
  {
    countryCode: 'TH',
    countryCodeNumber: 66,
    description: 'Thailand',
    isDeleted: false,
  },
  {
    countryCode: 'TE',
    countryCodeNumber: 0,
    description: 'Timor',
    isDeleted: false,
  },
  {
    countryCode: 'TG',
    countryCodeNumber: 228,
    description: 'Togo',
    isDeleted: false,
  },
  {
    countryCode: 'TK',
    countryCodeNumber: 690,
    description: 'Tokelau Islands',
    isDeleted: false,
  },
  {
    countryCode: 'TO',
    countryCodeNumber: 676,
    description: 'Tonga',
    isDeleted: false,
  },
  {
    countryCode: 'TT',
    countryCodeNumber: 1,
    description: 'Trinidad & Tobago',
    isDeleted: false,
  },
  {
    countryCode: 'TN',
    countryCodeNumber: 216,
    description: 'Tunisia',
    isDeleted: false,
  },
  {
    countryCode: 'TR',
    countryCodeNumber: 90,
    description: 'Turkey',
    isDeleted: false,
  },
  {
    countryCode: 'TM',
    countryCodeNumber: 993,
    description: 'Turkmenistan',
    isDeleted: false,
  },
  {
    countryCode: 'TC',
    countryCodeNumber: 1,
    description: 'Turks & Caicos Islands',
    isDeleted: false,
  },
  {
    countryCode: 'TV',
    countryCodeNumber: 688,
    description: 'Tuvalu',
    isDeleted: false,
  },
  {
    countryCode: 'UG',
    countryCodeNumber: 256,
    description: 'Uganda',
    isDeleted: false,
  },
  {
    countryCode: 'UR',
    countryCodeNumber: 380,
    description: 'Ukraine',
    isDeleted: false,
  },
  {
    countryCode: 'AE',
    countryCodeNumber: 971,
    description: 'United Arab Emirates',
    isDeleted: false,
  },
  {
    countryCode: 'GB',
    countryCodeNumber: 44,
    description: 'United Kingdom',
    isDeleted: false,
  },
  {
    countryCode: 'US',
    countryCodeNumber: 0,
    description: 'United States',
    isDeleted: false,
  },
  {
    countryCode: 'HV',
    countryCodeNumber: 0,
    description: 'Upper Volta',
    isDeleted: false,
  },
  {
    countryCode: 'UY',
    countryCodeNumber: 598,
    description: 'Uruguay',
    isDeleted: false,
  },
  {
    countryCode: 'VI',
    countryCodeNumber: 1,
    description: 'US Virgin Islands',
    isDeleted: false,
  },
  {
    countryCode: 'UZ',
    countryCodeNumber: 998,
    description: 'Uzbekistan',
    isDeleted: false,
  },
  {
    countryCode: 'VU',
    countryCodeNumber: 678,
    description: 'Vanuatu',
    isDeleted: false,
  },
  {
    countryCode: 'VA',
    countryCodeNumber: 0,
    description: 'Vatican City State',
    isDeleted: false,
  },
  {
    countryCode: 'VE',
    countryCodeNumber: 58,
    description: 'Venezuela',
    isDeleted: false,
  },
  {
    countryCode: 'VN',
    countryCodeNumber: 84,
    description: 'Vietnam',
    isDeleted: false,
  },
  {
    countryCode: 'WK',
    countryCodeNumber: 0,
    description: 'Wake Island',
    isDeleted: false,
  },
  {
    countryCode: 'WF',
    countryCodeNumber: 681,
    description: 'Wallis and Futuna',
    isDeleted: false,
  },
  {
    countryCode: 'EH',
    countryCodeNumber: 0,
    description: 'Western Sahara',
    isDeleted: false,
  },
  {
    countryCode: 'YM',
    countryCodeNumber: 967,
    description: 'Yemen',
    isDeleted: false,
  },
  {
    countryCode: 'YU',
    countryCodeNumber: 0,
    description: 'Yugoslavia',
    isDeleted: false,
  },
  {
    countryCode: 'ZR',
    countryCodeNumber: 0,
    description: 'Zaire',
    isDeleted: false,
  },
  {
    countryCode: 'ZM',
    countryCodeNumber: 260,
    description: 'Zambia',
    isDeleted: false,
  },
  {
    countryCode: 'ZW',
    countryCodeNumber: 263,
    description: 'Zimbabwe',
    isDeleted: false,
  },
];

export const SALARY_TYPES = [
  {
    description: 'Monthly',
    isDeleted: false,
    salaryTypeId: 4,
  },
  {
    description: 'Annual',
    isDeleted: false,
    salaryTypeId: 5,
  },
];

export const COMPANY_REGISTRATION_TYPES = [
  {
    description: 'Registry of Company',
    endDate: '2046-11-02T16:54:28.783',
    isDeleted: false,
    registrationTypeCode: 1,
    startDate: '2016-11-02T16:54:28.783',
  },
  {
    description: 'Registry of Business',
    endDate: '2046-11-02T16:54:28.783',
    isDeleted: false,
    registrationTypeCode: 2,
    startDate: '2016-11-02T16:54:28.783',
  },
  {
    description: 'Other Unique Establishments (UENO)',
    endDate: '2046-11-02T16:54:28.783',
    isDeleted: false,
    registrationTypeCode: 3,
    startDate: '2016-11-02T16:54:28.783',
  },
  {
    description: 'Others - None of the Above',
    endDate: '2046-11-02T16:54:28.783',
    isDeleted: false,
    registrationTypeCode: 4,
    startDate: '2016-11-02T16:54:28.783',
  },
];
